name: CI
on: push
jobs:
  test:
    strategy:
      # do not stop the matrix if one of the jobs fails
      fail-fast: false
      matrix:
        name: [foo, bar, baz]
    runs-on: ubuntu-latest
    outputs:
      passed_${{ strategy.job-index }}: ${{ steps.set1.outputs.passed }}
    # https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs
    steps:
      - name: Set output
        id: set1
        run: echo "passed=${{ matrix.name }}" >> "$GITHUB_OUTPUT"
  summary:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Print inputs
        run: echo ${{ toJSON(needs.test.outputs.passed) }}
